# Site wide configuration

title: Miha Rekar
locale: en_US
url: https://mr.si
enforce_ssl: mr.si

# Jekyll configuration

permalink:   pretty
markdown:    kramdown
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

# Site owner
owner:
  name: Miha Rekar
  avatar: miha-rekar.jpg
  email: info@mr.si
  disqus-shortname: miharekar
  twitter: MihaRekar
  facebook: rekar
  google:
    analytics: UA-356422-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: miharekar
  stackoverflow: 527840/miha-rekar
  linkedin: miha-rekar
  instagram: MihaRekar
  foursquare: mr_foto
  youtube: MihaRekar
  soundcloud: mr-foto
  speakerdeck: mrfoto

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
